// Code generated by "stringer -type=Operation -linecomment"; DO NOT EDIT.

package iceberg

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OpTrue-0]
	_ = x[OpFalse-1]
	_ = x[OpIsNull-2]
	_ = x[OpNotNull-3]
	_ = x[OpIsNan-4]
	_ = x[OpNotNan-5]
	_ = x[OpLT-6]
	_ = x[OpLTEQ-7]
	_ = x[OpGT-8]
	_ = x[OpGTEQ-9]
	_ = x[OpEQ-10]
	_ = x[OpNotEQ-11]
	_ = x[OpIn-12]
	_ = x[OpNotIn-13]
	_ = x[OpNot-14]
	_ = x[OpAnd-15]
	_ = x[OpOr-16]
	_ = x[OpStartsWith-17]
	_ = x[OpNotStartsWith-18]
	_ = x[OpCount-19]
	_ = x[OpCountStar-20]
	_ = x[OpMax-21]
	_ = x[OpMin-22]
}

const _Operation_name = "TrueFalseIsNullNotNullIsNaNNotNaNLessThanLessThanEqualGreaterThanGreaterThanEqualEqualNotEqualInNotInNotAndOrStartsWithNotStartsWithCountCountStarMaxMin"

var _Operation_index = [...]uint8{0, 4, 9, 15, 22, 27, 33, 41, 54, 65, 81, 86, 94, 96, 101, 104, 107, 109, 119, 132, 137, 146, 149, 152}

func (i Operation) String() string {
	if i < 0 || i >= Operation(len(_Operation_index)-1) {
		return "Operation(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Operation_name[_Operation_index[i]:_Operation_index[i+1]]
}
